import { IMAGES } from '../app/site-config.js';
import { pageHero, sectionHeading, ctaPanel } from '../app/components.js';
import { pageTitle, imageTag } from '../app/render-helpers.js';

export function renderWhitePapersPage() {
  pageTitle('White Papers');
  return `<main id="main-content">${pageHero({category:'Resources',title:'White Papers and technology perspectives',lead:'Structured thinking for leaders evaluating modernisation, data platforms, AI adoption, security and technology delivery. The purpose is to clarify decisions, trade-offs and implementation considerations before investment is committed.',image:IMAGES.whitePapers,imageAlt:'Professional research workspace with documents, laptop and handwritten notes',crumbs:[{label:'Home',href:'/'},{label:'White Papers'}]})}
    <section class="section"><div class="container split"><div>${imageTag(IMAGES.whitePapersDetail,'Professional reviewing research documents beside a laptop in a real office')}</div><div><span class="eyebrow">Research perspective</span><h2>Decision support, not trend commentary.</h2><p>Our resource themes are organised around questions technology leaders commonly need to answer: what should change, what should remain stable, what risks need to be controlled and what operating capability is required after implementation.</p><p>Material is structured to connect architecture, engineering, governance and business outcomes so the reader can move from a strategic topic to practical evaluation criteria.</p></div></div></section>
    <section class="section section--soft"><div class="container">${sectionHeading('Research themes','Technology and management topics with implementation depth','Each theme is framed around architecture choices, operating implications, delivery risk and the evidence required to make a defensible decision.')}
      <div class="topic-grid">
        <article class="topic-card resource-card"><span class="eyebrow">Cloud</span><h3>Cloud modernisation</h3><p>How to distinguish migration from genuine modernisation and evaluate workload fit, landing-zone controls, resilience, observability, operating ownership and cost governance.</p><ul><li>Migration strategy and dependency mapping</li><li>Platform foundations and DevSecOps</li><li>Resilience, SRE and operational readiness</li><li>FinOps and lifecycle governance</li></ul></article>
        <article class="topic-card resource-card"><span class="eyebrow">Data</span><h3>Data engineering</h3><p>How to build data platforms that users can trust, with reliable pipelines, clear ownership, observable quality and analytical models connected to real decisions.</p><ul><li>ETL/ELT and orchestration</li><li>Warehouse and lakehouse architecture</li><li>Data quality, lineage and governance</li><li>Analytics and semantic models</li></ul></article>
        <article class="topic-card resource-card"><span class="eyebrow">AI</span><h3>Responsible AI delivery</h3><p>How to move from experimentation to a governed production capability with explicit use cases, evaluation, human oversight, security, integration and operational monitoring.</p><ul><li>Use-case qualification and data readiness</li><li>Evaluation and acceptance thresholds</li><li>Security and human-review controls</li><li>MLOps/LLMOps and change management</li></ul></article>
      </div>
    </div></section>
    <section class="section"><div class="container">${sectionHeading('How to use these resources','Move from reading to a structured decision','If a theme maps to an active programme, use the consultation route to bring the specific environment, constraints and decision into the conversation.')}
      <div class="trust-strip"><div class="trust-item"><strong>Frame the question</strong><span>Identify the decision or risk the organisation is trying to resolve.</span></div><div class="trust-item"><strong>Assess the environment</strong><span>Bring current systems, dependencies, governance and operating constraints into scope.</span></div><div class="trust-item"><strong>Define the next action</strong><span>Translate the perspective into an assessment, architecture decision or delivery plan.</span></div></div>
    </div></section>${ctaPanel('Looking for a specific point of view?','Tell us the technology, management or industry decision you are evaluating and the context around it.')}</main>`;
}
