const SUPABASE_URL=Deno.env.get("SUPABASE_URL")??"";const LEGACY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";let MODERN="";try{const raw=Deno.env.get("SUPABASE_SECRET_KEYS");if(raw){const x=JSON.parse(raw);MODERN=String(x.default??Object.values(x)[0]??"");}}catch{}const API_KEY=LEGACY||MODERN;
async function rest(path:string,init:RequestInit={}):Promise<Response>{if(!SUPABASE_URL||!API_KEY)throw new Error("configuration unavailable");const h=new Headers(init.headers);h.set("apikey",API_KEY);if(LEGACY)h.set("authorization",`Bearer ${LEGACY}`);h.set("content-type","application/json");if(!h.has("prefer"))h.set("prefer","return=representation");return fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...init,headers:h});}
async function rows(r:Response):Promise<any[]>{if(!r.ok)throw new Error("database request failed");const b=await r.json();return Array.isArray(b)?b:[];}
export async function adminByEmail(email:string){const d=await rows(await rest(`admins?email=eq.${encodeURIComponent(email)}&status=eq.active&select=id,email,full_name,role,status,last_login_at,password_hash&limit=1`,{method:"GET"}));return d.length===1?d[0]:null;}
export async function adminById(id:string){const d=await rows(await rest(`admins?id=eq.${encodeURIComponent(id)}&status=eq.active&select=id,email,full_name,role,status,last_login_at&limit=1`,{method:"GET"}));return d.length===1?d[0]:null;}
export async function verifyPassword(id:string,password:string):Promise<boolean>{const r=await rest("rpc/verify_admin_password",{method:"POST",body:JSON.stringify({p_admin_id:id,p_password:password})});if(!r.ok)return false;const b=await r.json();return b===true||(Array.isArray(b)&&b[0]===true);}
export async function saveNewPassword(id:string,password:string):Promise<boolean>{const r=await rest("rpc/set_admin_password",{method:"POST",body:JSON.stringify({p_admin_id:id,p_password:password})});if(!r.ok)return false;const b=await r.json();return b===true||(Array.isArray(b)&&b[0]===true);}
export async function updateLastLogin(id:string){const d=await rows(await rest(`admins?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify({last_login_at:new Date().toISOString(),updated_at:new Date().toISOString()})}));if(d.length!==1)throw new Error("last login update failed");}
export async function createSession(data:Record<string,unknown>){const d=await rows(await rest("sessions",{method:"POST",body:JSON.stringify(data)}));if(d.length!==1)throw new Error("session create failed");return d[0];}
export async function sessionByHash(hash:string,idleCutoff:string){const now=new Date().toISOString();const d=await rows(await rest(`sessions?token_hash=eq.${encodeURIComponent(hash)}&revoked_at=is.null&expires_at=gt.${encodeURIComponent(now)}&last_seen_at=gt.${encodeURIComponent(idleCutoff)}&select=id,admin_id,csrf_token_hash,expires_at,last_seen_at&limit=1`,{method:"GET"}));return d.length===1?d[0]:null;}
export async function touchSession(id:string){const r=await rest(`sessions?id=eq.${encodeURIComponent(id)}&revoked_at=is.null`,{method:"PATCH",body:JSON.stringify({last_seen_at:new Date().toISOString()})});if(!r.ok)throw new Error("session touch failed");}
export async function revokeSession(id:string){const r=await rest(`sessions?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify({revoked_at:new Date().toISOString()})});if(!r.ok)throw new Error("session revoke failed");}
export async function revokeAllSessions(adminId:string){const r=await rest(`sessions?admin_id=eq.${encodeURIComponent(adminId)}&revoked_at=is.null`,{method:"PATCH",body:JSON.stringify({revoked_at:new Date().toISOString()})});if(!r.ok)throw new Error("session revoke failed");}
export async function audit(action:string,adminId:string|null,ipHash:string,userAgent:string,metadata:Record<string,unknown>){const r=await rest("audit_logs",{method:"POST",body:JSON.stringify({admin_id:adminId,action,entity_type:"authentication",ip_hash:ipHash,user_agent:userAgent,metadata})});if(!r.ok)throw new Error("audit failed");}
async function auditCount(action:string,ipHash:string,since:string,limit:number){const d=await rows(await rest(`audit_logs?action=eq.${encodeURIComponent(action)}&ip_hash=eq.${encodeURIComponent(ipHash)}&created_at=gte.${encodeURIComponent(since)}&select=id&limit=${limit}`,{method:"GET"}));return d.length;}
export async function failedCount(ipHash:string){return auditCount("admin_login_failed",ipHash,new Date(Date.now()-15*60_000).toISOString(),5);}
export async function resetRequestCount(ipHash:string){return auditCount("admin_password_reset_requested",ipHash,new Date(Date.now()-60*60_000).toISOString(),3);}
export async function queueResetRequest(adminId:string,email:string){const r=await rest("email_logs",{method:"POST",body:JSON.stringify({provider:"pending",template_key:"admin_password_reset",recipient_email:email,subject:"RC IT Services administrator password reset",status:"queued",metadata:{admin_id:adminId,purpose:"admin_password_reset",token_generation:"at_send_time",delivery_phase:13}})});if(!r.ok)throw new Error("reset queue failed");}
export async function resetByHash(hash:string){const now=new Date().toISOString();const d=await rows(await rest(`password_reset_tokens?token_hash=eq.${encodeURIComponent(hash)}&used_at=is.null&expires_at=gt.${encodeURIComponent(now)}&select=id,admin_id,expires_at&limit=1`,{method:"GET"}));return d.length===1?d[0]:null;}
export async function markResetUsed(id:string){const d=await rows(await rest(`password_reset_tokens?id=eq.${encodeURIComponent(id)}&used_at=is.null`,{method:"PATCH",body:JSON.stringify({used_at:new Date().toISOString()})}));if(d.length!==1)throw new Error("reset update failed");}
export async function invalidateResetTokens(adminId:string,exceptId?:string){let p=`password_reset_tokens?admin_id=eq.${encodeURIComponent(adminId)}&used_at=is.null`;if(exceptId)p+=`&id=neq.${encodeURIComponent(exceptId)}`;const r=await rest(p,{method:"PATCH",body:JSON.stringify({used_at:new Date().toISOString()})});if(!r.ok)throw new Error("reset invalidation failed");}
export async function dashboardSnapshot(adminId:string){const r=await rest("rpc/get_admin_dashboard_snapshot",{method:"POST",body:JSON.stringify({p_admin_id:adminId})});if(!r.ok)throw new Error("dashboard request failed");const b=await r.json();return Array.isArray(b)?b[0]??null:b;}
